name: Release to Nuget

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
      - name: Build
        run: dotnet build --configuration Release HangfireRecurringTimelinePage
        working-directory: ./HangfireRecurringTimeline
      - name: Create NuGet package
        run: dotnet pack -c Release HangfireRecurringTimelinePage /p:Version=${{ github.event.release.tag_name }} /p:PackageReleaseNotes="See https://github.com/jkrogbsoell/HangfireRecurringTimeline/releases/tag/${{ github.event.release.tag_name }}"
        working-directory: ./HangfireRecurringTimeline
      - name: Publish the package to Nuget
        run: dotnet nuget push HangfireRecurringTimelinePage/bin/Release/${{ github.event.release.tag_name }}.nupkg
        working-directory: ./HangfireRecurringTimeline
